LotW ADIF includes an unexpected tag at the end. This is now properly handled.
k0swe/adif-parser-ts pull request #366
Opened 2022-10-31 17:56 UTC by sd

2022-11-01 22:49 UTC, xylo04 requested changes
Oh yes, I've encountered this before on parsers for other languages. It's very frustrating that LotW includes this non-conformant tag.

2022-11-01 22:49 UTC, xylo04 commented on test/adif-parser.test.ts
> +    //expect(AdifParser.parseAdi(fileContent)).toEqual(JSON.parse(expected));
What's up with the commented-out expectation here?

2022-11-02 01:07 UTC, sd commented
let me fix that commented line and resubmit

On Tue, Nov 1, 2022 at 6:49 PM Chris Keller ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Oh yes, I've encountered this before on parsers for other languages. It's
> very frustrating that LotW includes this non-conformant tag.
> ------------------------------
>
> In test/adif-parser.test.ts
> <https://github.com/k0swe/adif-parser-ts/pull/366#discussion_r1010970486>:
>
> > @@ -119,6 +119,17 @@ describe('AdifParser', () => {
>      });
>      expect(AdifParser.parseAdi(fileContent)).toEqual(JSON.parse(expected));
>    });
> +
> +  it('can parse an ADI from Logbook of the World', () => {
> +    const fileContent = fs.readFileSync('test/data/lotw.adi', {
> +      encoding: 'ascii',
> +    });
> +    const expected = fs.readFileSync('test/data/lotw.json', {
> +      encoding: 'utf8',
> +    });
> +    console.log(JSON.stringify(AdifParser.parseAdi(fileContent)));
> +    //expect(AdifParser.parseAdi(fileContent)).toEqual(JSON.parse(expected));
>
> What's up with the commented-out expectation here?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/k0swe/adif-parser-ts/pull/366#pullrequestreview-1164146352>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAADAAWGLP3XUTVRDVA62LWGGM7LANCNFSM6AAAAAARTKISBM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-11-02 02:48 UTC, xylo04 approved these changes
Thank you!

2022-11-02 14:23 UTC, merged